services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "../data/mysql-data:/var/lib/mysql"
      - "./biblioteca-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql"
      - "./biblioteca-datos.sql:/docker-entrypoint-initdb.d/02-datos.sql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  python:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../api:/app"
    ports:
      - "8000:8000"
